export const $ = (id) => document.getElementById(id);

export const els = {
  openBtn:$('openBtn'), mergeBtn:$('mergeBtn'), insertBtn:$('insertBtn'), insertImageBtn:$('insertImageBtn'), wordBtn:$('wordBtn'), exportBtn:$('exportBtn'), compressBtn:$('compressBtn'),
  fileInput:$('fileInput'), mergeInput:$('mergeInput'), insertInput:$('insertInput'), imageInput:$('imageInput'),
  libStatus:$('libStatus'), docStatus:$('docStatus'), pageCount:$('pageCount'), thumbList:$('thumbList'), viewer:$('viewer'), dropHint:$('dropHint'),
  stageWrap:$('stageWrap'), pagesContainer:$('pagesContainer'), stage:$('stage'), canvas:$('pdfCanvas'), overlay:$('overlay'), textHitLayer:$('textHitLayer'),
  undoBtn:$('undoBtn'), redoBtn:$('redoBtn'), rotateLeftBtn:$('rotateLeftBtn'), rotateRightBtn:$('rotateRightBtn'), deletePageBtn:$('deletePageBtn'),
  zoomOutBtn:$('zoomOutBtn'), zoomInBtn:$('zoomInBtn'), fitBtn:$('fitBtn'), zoomLabel:$('zoomLabel'), prevBtn:$('prevBtn'), nextBtn:$('nextBtn'), pageLabel:$('pageLabel'),
  blockColor:$('blockColor'), textColor:$('textColor'), fontSize:$('fontSize'), fontFamily:$('fontFamily'), boldText:$('boldText'), italicText:$('italicText'), underlineText:$('underlineText'), textAlign:$('textAlign'), textValue:$('textValue'),
  applyTextBtn:$('applyTextBtn'), cancelModeBtn:$('cancelModeBtn'), deleteObjectBtn:$('deleteObjectBtn'), watermarkBtn:$('watermarkBtn'), movePageUpBtn:$('movePageUpBtn'), movePageDownBtn:$('movePageDownBtn'), clearMetadata:$('clearMetadata'), organizeBtn:$('organizeBtn'),
  textEditDialog:$('textEditDialog'), originalTextValue:$('originalTextValue'), replacementTextValue:$('replacementTextValue'), confirmReplaceTextBtn:$('confirmReplaceTextBtn'),
  watermarkDialog:$('watermarkDialog'), watermarkText:$('watermarkText'), watermarkSize:$('watermarkSize'), watermarkColor:$('watermarkColor'), watermarkOpacity:$('watermarkOpacity'), watermarkRotation:$('watermarkRotation'), watermarkScope:$('watermarkScope'), confirmWatermarkBtn:$('confirmWatermarkBtn'),
  pageNumberBtn:$('pageNumberBtn'), pageNumberStatus:$('pageNumberStatus'), pageNumberDialog:$('pageNumberDialog'), pageNumberPosition:$('pageNumberPosition'), pageNumberFormat:$('pageNumberFormat'), pageNumberFromPage:$('pageNumberFromPage'), pageNumberStart:$('pageNumberStart'), pageNumberSize:$('pageNumberSize'), pageNumberMargin:$('pageNumberMargin'), pageNumberColor:$('pageNumberColor'), confirmPageNumberBtn:$('confirmPageNumberBtn'), removePageNumbersBtn:$('removePageNumbersBtn'),
  wordDialog:$('wordDialog'), confirmWordBtn:$('confirmWordBtn'), organizerDialog:$('organizerDialog'), organizerGrid:$('organizerGrid'), addPageBtn:$('addPageBtn'), addPageDialog:$('addPageDialog'), addPagePosition:$('addPagePosition'), addPageSize:$('addPageSize'), addPageCount:$('addPageCount'), confirmAddPageBtn:$('confirmAddPageBtn'),
  performanceMode:$('performanceMode'), performanceStatus:$('performanceStatus'), autoSaveStatus:$('autoSaveStatus'),
  orgSelectAllBtn:$('orgSelectAllBtn'), orgClearBtn:$('orgClearBtn'), orgRotateLeftBtn:$('orgRotateLeftBtn'), orgRotateRightBtn:$('orgRotateRightBtn'), orgDuplicateBtn:$('orgDuplicateBtn'), orgDeleteBtn:$('orgDeleteBtn'), orgSelectionStatus:$('orgSelectionStatus'),
  recoveryDialog:$('recoveryDialog'), recoveryInfo:$('recoveryInfo'), restoreRecoveryBtn:$('restoreRecoveryBtn'), discardRecoveryBtn:$('discardRecoveryBtn'),
  saveProjectBtn:$('saveProjectBtn'), openProjectBtn:$('openProjectBtn'), projectInput:$('projectInput'), jumpPageInput:$('jumpPageInput'), jumpPageBtn:$('jumpPageBtn'), snapEnabled:$('snapEnabled'), objectSelectionStatus:$('objectSelectionStatus'), lockObjectBtn:$('lockObjectBtn'), bringFrontBtn:$('bringFrontBtn'), sendBackBtn:$('sendBackBtn'), preflightDialog:$('preflightDialog'), preflightSummary:$('preflightSummary'), confirmExportBtn:$('confirmExportBtn'), privacyWarningDialog:$('privacyWarningDialog'), privacyWarningSummary:$('privacyWarningSummary'), privacyProceedBtn:$('privacyProceedBtn'), blockSafetyHint:$('blockSafetyHint'), metadataPrivacyStatus:$('metadataPrivacyStatus'),
  compressionDialog:$('compressionDialog'), compressionMode:$('compressionMode'), compressionDpi:$('compressionDpi'), compressionQuality:$('compressionQuality'), compressionQualityValue:$('compressionQualityValue'), compressionSourceSize:$('compressionSourceSize'), compressionPresetInfo:$('compressionPresetInfo'), compressionAcknowledge:$('compressionAcknowledge'), confirmCompressionBtn:$('confirmCompressionBtn'),
  toast:$('toast'), busy:$('busy'), busyText:$('busyText'), busyDetail:$('busyDetail'), busyProgress:$('busyProgress'), busyCancelBtn:$('busyCancelBtn'), hintText:$('hintText'), sidePrevBtn:$('sidePrevBtn'), sideNextBtn:$('sideNextBtn')
};
