import {defaultPageNumber} from './config.js';

export const state = {
  sources: [],
  pages: [],
  currentIndex: 0,
  zoom: 1.15,
  tool: 'select',
  selectedAnnotationId: null,
  selectedAnnotationIds: new Set(),
  snapEnabled: true,
  undo: [],
  redo: [],
  renderToken: 0,
  thumbObserver: null,
  draggingPageId: null,
  organizerDraggingPageId: null,
  fileName: 'edited.pdf',
  pendingTextHit: null,
  textCache: new Map(),
  imageCache: new Map(),
  pageObserver: null,
  organizerObserver: null,
  pageRenderPromises: new Map(),
  pageRenderQueue: [],
  pageRenderQueued: new Set(),
  pageRenderWorkers: 0,
  organizerRenderQueue: [],
  organizerRenderQueued: new Set(),
  organizerRenderWorkers: 0,
  scrollRaf: 0,
  scrollIdleTimer: 0,
  isScrolling: false,
  performanceMode: 'auto',
  organizerSelection: new Set(),
  organizerLastSelectedIndex: -1,
  annotationClipboard: null,
  autosaveTimer: 0,
  autosaveSuspended: false,
  recoveryAvailable: null,
  recoveryDisabled: false,
  recoverySourceSignature: '',
  githubPrivacyMode: false,
  editRevision: 0,
  savedRevision: 0,
  virtualRebuildPending: false,
  operation: null,
  pageNumber: defaultPageNumber(),
};
